#!/usr/bin/env ruby

puts "Bundling..."
system %{bundle}

puts "Installing git hooks"
system %{script/install-git-hooks}

bundle = File.file?('Gemfile') ? 'bundle exec' : ''

command = [ bundle, 'rake', '-s', '-T', 'bootstrap' ]

if !(%x{#{command.join(' ')}}).empty?
  puts "Trying to run rake bootstrap..."
  system %{#{bundle} rake bootstrap}
end

puts "Done!"

