#!/usr/bin/env ruby

require 'rubygems'
require 'penchant'

if Penchant::Gemfile.do_full_env_switch!(ARGV[0], true)
  system %{bundle}
  puts "Gemfile switched to #{ARGV[0]} in deployment mode"
else
  exit 0
end

