#!/bin/bash

msg=$(cat $1)

OLD_GIT_DIR=$GIT_DIR

if [[ "${msg}" != *"[ci skip]"* ]]; then
  if [ "$(penchant gemfile-env)" != "remote" ]; then
    penchant gemfile remote
  fi

  bundle exec rake
  R=$?
  if [ $R -ne 0 ]; then exit $R; fi
fi

