#!/bin/bash

msg=$(cat $1)

# wtf mac os x lion
if [ ! -z "$MY_RUBY_HOME" ]; then
  PATH="$MY_RUBY_HOME/bin:$PATH"
fi

if [[ "${msg}" != *"[ci skip]"* ]]; then
  bundle exec rake --trace
  R=$?
  if [ $R -ne 0 ]; then exit $R; fi
fi

