@fakefs
Feature: Gemfiles
  Scenario: When rebuilding for deployment, save the original state
    Given I have the file "Gemfile.erb" with the content:
      """
      this is content
      """
      And I have the file "Gemfile" with the content:
      """
      # generated by penchant, environment: local
      """
    When I rebuild the Gemfile for "production" mode with deployment
    Then the file "Gemfile" should have the following content:
      """
      # generated by penchant, environment: production, deployment mode (was local)
      this is content
      """

  Scenario: When unbundling from deployment with an original state, switch to that state
    Given I have the file "Gemfile.erb" with the content:
      """
      this is content
      """
      And I have the file "Gemfile" with the content:
      """
      # generated by penchant, environment: production, deployment mode (was local)
      """
    When I rebuild the Gemfile asking to switch back to the previous state
    Then the file "Gemfile" should have the following content:
      """
      # generated by penchant, environment: local
      this is content
      """
