#!/bin/bash

if [ $(bundle exec rake -P | grep preflight_check | wc -l) -ne 0 ]; then
  bundle exec rake preflight_check
  R=$?
  if [ $R -ne 0 ]; then exit $R; fi
fi

unset GIT_DIR
penchant gemfile remote --deployment
GIT_DIR=$OLD_GIT_DIR
git add Gemfile*

exit 0
